# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

jobs:
  - job: Windows
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@0

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - script: |
            mkdir $(Agent.BuildDirectory)\netcdf
            cd $(Agent.BuildDirectory)\netcdf
            echo Start download from $(url_NetCDF_win)
            powershell Invoke-WebRequest $(url_NetCDF_win) -OutFile netcdf.exe
            echo Download succeeded.
            7z x netcdf.exe
      displayName: 'Download NetCDF library from UCAR web site'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
      env:
        PATH: '$(PATH);$(Agent.BuildDirectory)\netcdf\bin'
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:

    
    - bash: sudo apt install -y netcdf

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
